### ISSUE TITLE
request

### ISSUE THREAD

**Issue by Ragzouken** [nicelgbt/requests#2]
_My desired repository name_: kooltool

_About me_: im a nb games adjacent person tryna make tools n whatever else for fun

_Subdomain name: kooltool

**Comment by fene** [comment]
done! http://github.com/nicelgbt/kooltool (subdomain should be up)

**Comment by fene** [comment]
don't forget to add a `CNAME` file!

**Comment by Ragzouken** [comment]
thanks!
