### ISSUE TITLE
wave hello

### ISSUE THREAD

**Issue by Fidgette** [nicelgbt/requests#5]
_My desired repository name_: fidgettt

_About me_: there's a lot to learn and a lot of head fog to fight.

_Subdomain name (leave empty if you don't want one)_: fidgettt

Um alright! This is a lot to take in but worth trying I think. Seems like a very Nice setup! Is the About Me just to catch bots making sites or something?

**Comment by fene** [comment]
yep, pretty much! hang on, i'm setting you up

**Comment by fene** [comment]
https://github.com/nicelgbt/fidgettt here you go!
