### ISSUE TITLE
bubsy is a hero of free speech and also gay and poly

### ISSUE THREAD

**Issue by Moth-Tolias** [nicelgbt/requests#6]
_Desired repository name_: /mothtolias

if it's possible i would prefer to use the subdomain below, but this is cool if not

_About me_: music dev, sutolias on twitter. we've talked in passing a couple of times

_Subdomain name (leave empty if you don't want one)_: moth

**Comment by fene** [comment]
https://github.com/nicelgbt/mothtolias

check your email for a collaboration invitation thingy for the repo so that you can actually push to it!

**Comment by Moth-Tolias** [comment]
thank you!!

wow, i didn't think you'd get around to it so fast

**Comment by fene** [comment]
im fast
